version: '3'
services:
  rabbitmq:
    container_name: rabbitmq-golang
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=golang
      - RABBITMQ_DEFAULT_PASS=g0l4g